### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by luben** [antoyo/tokio-serde-bincode#2]
Hi,

@alexcrichton proposed  to transfer https://github.com/alexcrichton/tokio-serde-bincode to me so I can maintain it.

I have recently updates some of dependencies https://github.com/alexcrichton/tokio-serde-bincode/pull/7() and resolved some of the issues (similar to https://github.com/antoyo/tokio-serde-bincode/issues/1).

Are you interested in the project yourself? Or we can merge the good parts of your repo with alex's repo and have one crate from now on? I volunteer to maintain it.

Regards,
luben

**Comment by antoyo** [comment]
I'm not interested in maintaining this anymore.
If you don't mind, I'll add you to the owners on crates.io.
Is that okay with you?

**Comment by luben** [comment]
Yes, that's great. I will release version 0.2 with updated dependencies (based on the alex's version) and will add the examples from your repo if you don't mind.

Thanks in advance!

**Comment by antoyo** [comment]
I've invited you to become an owner of the crate.
Please close this issue when you accept it.

**Comment by luben** [comment]
Thanks!
